# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ib8mnmnCZbOTxrCxe2E7XsdCSGsM5MgY
"""

from google.colab import drive
drive.mount('/content/drive/')

import os
os.chdir("drive/My Drive/") 
!pwd

!unzip ERNIE_zh.zip
!cp merge.bin ERNIE_zh/pretrain_data
!cp merge.idx ERNIE_zh/pretrain_data
!cp vocab.txt ERNIE_zh/pretrain_data/ernie_base
!cp entity2id.txt ERNIE_zh/pretrain_data/kg_embed
!cp entity2vec.vec ERNIE_zh/pretrain_data/kg_embed

import os
os.chdir("ERNIE_zh") 
!pwd
!ls

!pip install apex
!pip uninstall apex

!git clone https://www.github.com/nvidia/apex

import os
os.chdir("apex")

!python setup.py install --record record.log

!cat record.log | xargs rm -rf

!pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

import os
os.chdir("../") 
!python code/run_pretrain.py --do_train --data_dir pretrain_data/merge --bert_model pretrain_data/ernie_base --output_dir pretrain_out/ --task_name pretrain --fp16 --max_seq_length 256

import os
os.chdir("/content/drive/My Drive/ERNIE_zh/")
!rm -rf pretrain_out
!python code/run_pretrain.py --do_train --data_dir pretrain_data/merge --bert_model pretrain_data/bert_chinese --output_dir pretrain_out/ --task_name pretrain --fp16 --max_seq_length 256

!cp -r /tmp/tmp765q3uzj ./

ls

!cp pretrain_data/ernie_base/ernie_config.json pretrain_data/bert_chinese/

ls /tmp/tmpnsbw7b7l/